import './globals.css'
import type { Metadata } from 'next'
import { ThemeProvider } from '@/components/theme-provider'
import { ReactNode } from 'react'
import { NavbarComponent } from '@/components/navbar'
import { Sidenav } from '@/components/sidenav'

export const metadata: Metadata = {
  title: 'Backoffice',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className="bg-gray-100 dark:bg-gray-950"
        suppressHydrationWarning={true}
      >
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <NavbarComponent.Root />
          <Sidenav.Root />
          <div className="p-0 xl:ml-64">{children}</div>
        </ThemeProvider>
      </body>
    </html>
  )
}
