import './globals.css'
import type { Metadata } from 'next'
import { ReactNode } from 'react'
import { RootContext } from '@/contexts/root.context'

export const metadata: Metadata = {
  title: 'Backoffice',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className="bg-gray-100 dark:bg-gray-950"
        suppressHydrationWarning={true}
      >
        <RootContext>{children}</RootContext>
      </body>
    </html>
  )
}
